[project]
name = "Shiftly"
version = "0.1.0"
description = "A shift-scheduling & swap system"
requires-python = ">=3.11"
dependencies = [
    "django-filter>=26.1",
    "djangorestframework-simplejwt>=5.5.1",
    "dotenv>=0.9.9",
    "psycopg2>=2.9.13",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
asyncio_default_test_loop_scope = "session"
asyncio_default_fixture_loop_scope = "session"
