# Generated by Django 6.1.1 on 2026-09-29 21:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Postgres has no bigint -> uuid cast, so map each id to a zero-padded uuid
# (e.g. 1 -> 00000000-0000-0000-0000-000000000001). The same expression is
# applied to the PK and every FK column pointing at it, keeping references intact.
BIGINT_TO_UUID_USING_SQL = " USING lpad(to_hex(%(column)s), 32, '0')::uuid"


class AlterIdToUUID(migrations.AlterField):
    """AlterField that can convert a bigint PK (and its incoming FKs) to uuid."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor != 'postgresql':
            return super().database_forwards(app_label, schema_editor, from_state, to_state)

        connection = schema_editor.connection
        default_using_sql = schema_editor._using_sql

        def using_sql(new_field, old_field):
            if (
                old_field.db_parameters(connection=connection)['type'] == 'bigint'
                and new_field.db_parameters(connection=connection)['type'] == 'uuid'
            ):
                return BIGINT_TO_UUID_USING_SQL
            return default_using_sql(new_field, old_field)

        schema_editor._using_sql = using_sql
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        finally:
            del schema_editor._using_sql


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        # django_admin_log.user_id references employees.id and must be converted too.
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [  # noqa: RUF012
        AlterIdToUUID(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        AlterIdToUUID(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        AlterIdToUUID(
            model_name='shift',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shiftclaim',
            name='claimed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_by_shift_claims', related_query_name='claimed_by_shift_claim', to=settings.AUTH_USER_MODEL),
        ),
        AlterIdToUUID(
            model_name='shiftclaim',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shiftclaim',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shift_claims', related_query_name='shift_claim', to='app.shift'),
        ),
        AlterIdToUUID(
            model_name='swaprequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='resolved_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='target_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.shift'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='idx_employee_email'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['first_name'], name='idx_employee_first_name'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name'], name='idx_employee_last_name'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['date_joined'], name='idx_employee_date_joined'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['start_time'], name='idx_shift_start_time'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['end_time'], name='idx_shift_end_time'),
        ),
        migrations.AddIndex(
            model_name='shiftclaim',
            index=models.Index(fields=['created_at'], name='idx_shift_claim_created_at'),
        ),
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(fields=['created_at'], name='idx_swap_request_created_at'),
        ),
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(fields=['resolved_at'], name='idx_swap_request_resolved_at'),
        ),
    ]
