# Generated by Django 6.1.1 on 2026-10-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_department_id_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaprequest',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
